version: "3.8"

services:
  postgres:
    image: postgres:12.7
    container_name: postgres_12_7
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - my_personal_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  my_personal_network:   # 👈 definición de la red
    driver: bridge
